### ISSUE TITLE
Error after impor

### ISSUE THREAD

**Issue by devnextdoorcoders** [invisiburu/vue-picker#11]
Hi.
I install this component via npm.
But if I import it to my project, I have next error:
`Uncaught TypeError: Object(...) is not a function
    <anonymous> http://smart-local/js/app.js:114829
    <anonymous> http://smart-local/js/app.js:114960
    __webpack_require__ http://smart-local/js/app.js:20
    <anonymous> http://smart-local/js/app.js:114394
    __webpack_require__ http://smart-local/js/app.js:20
    <anonymous> http://smart-local/js/app.js:114307
    __webpack_require__ http://smart-local/js/app.js:20
    <anonymous> http://smart-local/js/app.js:110646
    __webpack_require__ http://smart-local/js/app.js:20
    <anonymous> http://smart-local/js/app.js:110622
    __webpack_require__ http://smart-local/js/app.js:20
    <anonymous> http://smart-local/js/app.js:63
    <anonymous> http://smart-local/js/app.js:66
app.js:114829:87
    <anonymous> http://smart-local/js/app.js:114829
    <anonymous> http://smart-local/js/app.js:114960
    __webpack_require__ http://smart-local/js/app.js:20
    <anonymous> http://smart-local/js/app.js:114394
    __webpack_require__ http://smart-local/js/app.js:20
    <anonymous> http://smart-local/js/app.js:114307
    __webpack_require__ http://smart-local/js/app.js:20
    <anonymous> http://smart-local/js/app.js:110646
    __webpack_require__ http://smart-local/js/app.js:20
    <anonymous> http://smart-local/js/app.js:110622
    __webpack_require__ http://smart-local/js/app.js:20
    <anonymous> http://smart-local/js/app.js:63
    <anonymous> http://smart-local/js/app.js:66
`

Its a header of my code:
`import { VuePicker, VuePickerOption } from '@invisiburu/vue-picker' 
import '@invisiburu/vue-picker/dist/vue-picker.min.css'
export default {
    name: "ExchangeHomeForm",
    components: {
        VuePicker,
        VuePickerOption
    },
    mixins: [MainMixin],`
    
    I not insert any <vue-picker> components in my code.
    
    Can you help me to run this component?

**Comment by invisiburu** [comment]
Hey @devnextdoorcoders 

Thanks for reporting the issue. I resolved the same one recently.

Please, try upgrading your `npm` version (tested with the 7.19.1) and generate a new `package-lock.json`.

To re-generate the `package-lock.json`, please remove the `node_modules/` directory and the `package-lock.json` itself. Then just run the `npm i`.

```bash
npm install -g npm@latest
rm -rf node_modules/ package-lock.json
npm i
```
I am not sure about the reason, to be honest. It seems `npm` failed to resolve the peer dependencies. Probably some `npm` update made this process work in a new way that is incompatible with your current `package-lock.json` version.
